In [2]:
import pandas as pd
import numpy as np
fname = 'data2.csv'
df = pd.read_csv(fname)


# print(df)
for x in range(len(df['Age'])):
  if df["Age"][x] > 81:
    df["Age"][x] = np.nan
df
# df.to_csv("\content\modified.csv",index=True)

/tmp/ipykernel_5135/1259192988.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["Age"][x] = np.nan
/tmp/ipykernel_5135/1259192988.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"][x] = np.nan

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Tiffany Ramirez,81.0,Female,O-,Diabetes,11/17/2022,Patrick Parker,Wallace-Hamilton,Medicare,37490.983360,146.0,Elective,12/1/2022,Aspirin,Inconclusive
1,Ruben Burns,35.0,Male,O+,Asthma,6/1/2023,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064850,404.0,Emergency,6/15/2023,Lipitor,Normal
2,Chad Byrd,61.0,Male,B-,Obesity,1/9/2019,Paul Baker,Walton LLC,Medicare,36874.897000,292.0,Emergency,2/8/2019,Lipitor,Normal
3,Antonio Frederick,49.0,Male,B-,Asthma,5/2/2020,Brian Chandler,Garcia Ltd,Medicare,23303.322090,NaN,Urgent,5/3/2020,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51.0,Male,O-,Arthritis,7/9/2021,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344180,477.0,Urgent,8/2/2021,Paracetamol,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,James Hood,NaN,Male,A+,Obesity,7/29/2022,Samuel Moody,"Wood, Martin and Simmons",UnitedHealthcare,39606.840080,110.0,Elective,8/2/2022,Ibuprofen,Abnormal
9996,Stephanie Evans,47.0,Female,AB+,Arthritis,1/6/2022,Christopher Yates,Nash-Krueger,Blue Cross,5995.717488,244.0,Emergency,1/29/2022,Ibuprofen,Normal
9997,Christopher Martinez,54.0,Male,B-,Arthritis,7/1/2022,Robert Nicholson,Larson and Sons,Blue Cross,49559.202900,312.0,Elective,7/15/2022,Ibuprofen,Normal
9998,Amanda Duke,NaN,Male,A+,Arthritis,NaN,Jamie Lewis,Wilson-Lyons,UnitedHealthcare,25236.344760,420.0,Urgent,2/26/2020,Penicillin,Normal
9999,Eric King,20.0,Male,B-,Arthritis,3/22/2023,Tasha Avila,"Torres, Young and Stewart",Aetna,37223.965860,NaN,Emergency,4/15/2023,Penicillin,Abnormal

In [3]:
import math
#method 1 if empty values
# 1. delete row
# 2. create random
# disadv data outliers
# (3.) add avg

sum=0
num=0
for i in range(len(df["Age"])):
  if math.isnan(df["Age"][i]) == False:
    num += 1
    sum += int(df["Age"][i])
print(num,"faults")
print(len(df["Age"]),"data size")
avg = int(sum/num)

if len(df["Age"])!=num:
  print(f"replacing faults with {avg}")

  # for i in range(len(df["Age"])):
  #   if math.isnan(df["Age"][i]) == True:
  #     # print("fixing: ",df.loc[[i]])
  #     df.iloc[i, "Age"] = avg

  df['Age']=df['Age'].apply(lambda x:avg if(math.isnan(x)) else x)
  print("\n\n\done\n\n\n")
else:
  print("no faults")

9466 faults
10000 data size
replacing faults with 49


\done

In [4]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Tiffany Ramirez,81.0,Female,O-,Diabetes,11/17/2022,Patrick Parker,Wallace-Hamilton,Medicare,37490.983360,146.0,Elective,12/1/2022,Aspirin,Inconclusive
1,Ruben Burns,35.0,Male,O+,Asthma,6/1/2023,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064850,404.0,Emergency,6/15/2023,Lipitor,Normal
2,Chad Byrd,61.0,Male,B-,Obesity,1/9/2019,Paul Baker,Walton LLC,Medicare,36874.897000,292.0,Emergency,2/8/2019,Lipitor,Normal
3,Antonio Frederick,49.0,Male,B-,Asthma,5/2/2020,Brian Chandler,Garcia Ltd,Medicare,23303.322090,NaN,Urgent,5/3/2020,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51.0,Male,O-,Arthritis,7/9/2021,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344180,477.0,Urgent,8/2/2021,Paracetamol,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,James Hood,49.0,Male,A+,Obesity,7/29/2022,Samuel Moody,"Wood, Martin and Simmons",UnitedHealthcare,39606.840080,110.0,Elective,8/2/2022,Ibuprofen,Abnormal
9996,Stephanie Evans,47.0,Female,AB+,Arthritis,1/6/2022,Christopher Yates,Nash-Krueger,Blue Cross,5995.717488,244.0,Emergency,1/29/2022,Ibuprofen,Normal
9997,Christopher Martinez,54.0,Male,B-,Arthritis,7/1/2022,Robert Nicholson,Larson and Sons,Blue Cross,49559.202900,312.0,Elective,7/15/2022,Ibuprofen,Normal
9998,Amanda Duke,49.0,Male,A+,Arthritis,NaN,Jamie Lewis,Wilson-Lyons,UnitedHealthcare,25236.344760,420.0,Urgent,2/26/2020,Penicillin,Normal
9999,Eric King,20.0,Male,B-,Arthritis,3/22/2023,Tasha Avila,"Torres, Young and Stewart",Aetna,37223.965860,NaN,Emergency,4/15/2023,Penicillin,Abnormal

In [5]:
min=df['Room Number'][0]
max=df['Room Number'][0]
num=0
for i in range(len(df['Room Number'])):
  if math.isnan(df["Room Number"][i]) == False:
    num+=1
    if max<df['Room Number'][i]:
      max=df['Room Number'][i]
    if min>df['Room Number'][i]:
      min=df['Room Number'][i]

if len(df["Room Number"])!=num:
  print(f"Nan found on [Room Number] repalcing with {int((max+min)/2)}")
  df['Room Number']=df['Room Number'].apply(lambda x:float(int((max+min)/2)) if(math.isnan(x)) else x)

else:
  print("no data is cleaned")

Nan found on [Room Number] repalcing with 300

In [6]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Tiffany Ramirez,81.0,Female,O-,Diabetes,11/17/2022,Patrick Parker,Wallace-Hamilton,Medicare,37490.983360,146.0,Elective,12/1/2022,Aspirin,Inconclusive
1,Ruben Burns,35.0,Male,O+,Asthma,6/1/2023,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064850,404.0,Emergency,6/15/2023,Lipitor,Normal
2,Chad Byrd,61.0,Male,B-,Obesity,1/9/2019,Paul Baker,Walton LLC,Medicare,36874.897000,292.0,Emergency,2/8/2019,Lipitor,Normal
3,Antonio Frederick,49.0,Male,B-,Asthma,5/2/2020,Brian Chandler,Garcia Ltd,Medicare,23303.322090,300.0,Urgent,5/3/2020,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51.0,Male,O-,Arthritis,7/9/2021,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344180,477.0,Urgent,8/2/2021,Paracetamol,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,James Hood,49.0,Male,A+,Obesity,7/29/2022,Samuel Moody,"Wood, Martin and Simmons",UnitedHealthcare,39606.840080,110.0,Elective,8/2/2022,Ibuprofen,Abnormal
9996,Stephanie Evans,47.0,Female,AB+,Arthritis,1/6/2022,Christopher Yates,Nash-Krueger,Blue Cross,5995.717488,244.0,Emergency,1/29/2022,Ibuprofen,Normal
9997,Christopher Martinez,54.0,Male,B-,Arthritis,7/1/2022,Robert Nicholson,Larson and Sons,Blue Cross,49559.202900,312.0,Elective,7/15/2022,Ibuprofen,Normal
9998,Amanda Duke,49.0,Male,A+,Arthritis,NaN,Jamie Lewis,Wilson-Lyons,UnitedHealthcare,25236.344760,420.0,Urgent,2/26/2020,Penicillin,Normal
9999,Eric King,20.0,Male,B-,Arthritis,3/22/2023,Tasha Avila,"Torres, Young and Stewart",Aetna,37223.965860,300.0,Emergency,4/15/2023,Penicillin,Abnormal

In [41]:
df.to_csv("new.csv", sep=',')

Vim: Warning: Output is not to a terminal